- &hook
  id: nbdev_clean
  name: nbdev_clean
  entry: nbdev_clean
  description: "Clean metadata from notebooks to avoid merge conflicts"
  language: system
  always_run: true
  pass_filenames: false

- <<: *hook
  id: nbdev_export
  name: nbdev_export
  entry: nbdev_export
  description: "Export notebooks to modules and build modidx"

