wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: huggingface
    huggingface_version: 4.22.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1665199706.704097
    t:
      1:
      - 1
      - 4
      - 5
      - 11
      - 35
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 23
      4: 3.10.6
      5: 0.13.3
      6: 4.22.1
      8:
      - 1
      - 5
