# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/fsdl_2022_course_project',
                'doc_host': 'https://ohmeow.github.io',
                'git_url': 'https://github.com/ohmeow/fsdl_2022_course_project',
                'lib_path': 'fsdl_2022_course_project'},
  'syms': {'fsdl_2022_course_project.core': {'fsdl_2022_course_project.core.foo': ('core.html#foo', 'fsdl_2022_course_project/core.py')}}}