# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/course_copilot',
                'doc_host': 'https://ohmeow.github.io',
                'git_url': 'https://github.com/ohmeow/fsdl_2022_course_project',
                'lib_path': 'course_copilot'},
  'syms': {'course_copilot.core': {'course_copilot.core.foo': ('core.html#foo', 'course_copilot/core.py')}}}