# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/30_summarization.ipynb.

# %% ../nbs/30_summarization.ipynb 3
from __future__ import annotations

import os, warnings

from fastcore.all import *
from fastai.imports import *
from fastai.torch_core import *
from fastai.torch_imports import *
from transformers.utils import logging as hf_logging

from . import utils, training

# %% auto 0
__all__ = []

# %% ../nbs/30_summarization.ipynb 5
# silence all the HF warnings
warnings.simplefilter("ignore")
hf_logging.set_verbosity_error()
